// Code generated by protoc-gen-gocraft. DO NOT EDIT.
//
// Source: abi/v1/events.proto

package gocraft

import (
	"fmt"

	abi "github.com/GoCraft-MC/gocraft-abi/abi/v1"
)

// Event types, as a manifest spells them.
const (
	// Cancellable, blocks the tick, defaults to allow. Introduced in ABI 1.
	EventBlockBreak = "block.break"
	// Observational, never cancelled. Introduced in ABI 1.
	EventPlayerJoin = "player.join"
)

// BlockBreakEvent is the block.break event.
//
// Cancellable, and dispatched while the tick waits. Every subscriber
// shares one budget for the whole event, so a handler that takes its
// time is taking it from the others.
type BlockBreakEvent struct {
	Player Player
	Pos    BlockPos
	Block  Block
	Tool   string

	// permissions is what the host resolved before dispatch. Unexported
	// because the schema says an injected field surfaces as a query
	// rather than as a map to rummage through, and because a handler
	// that could write to it would be answering its own question.
	permissions map[string]bool

	cancelled bool
}

func (*BlockBreakEvent) Type() string { return EventBlockBreak }

// Can reports whether the acting player holds a permission node.
//
// Already resolved: the host answers every node the manifest subscribed
// to and ships the answers inside the event, so this is a map lookup
// rather than a round trip taken while the tick waits.
//
// A node the manifest never declared reads false, because the host was
// never asked about it. That is a manifest bug, not a denial.
func (e *BlockBreakEvent) Can(node string) bool { return e.permissions[node] }

// Cancel prevents the action. The host decides the outcome once every
// subscriber has answered or the budget has run out.
func (e *BlockBreakEvent) Cancel() { e.cancelled = true }

func (e *BlockBreakEvent) Cancelled() bool { return e.cancelled }

// OnBlockBreak registers a handler for block.break.
//
// Typed, so there is no event name to misspell: the parameter is the
// subscription. On accepts a name for anything this build does not know.
func (e *Events) OnBlockBreak(handler func(*BlockBreakEvent)) error {
	return e.On(EventBlockBreak, func(event Event) {
		if typed, ok := event.(*BlockBreakEvent); ok {
			handler(typed)
		}
	})
}

func blockBreakFrom(fields []abi.Value) (*BlockBreakEvent, error) {
	if len(fields) != 5 {
		return nil, fmt.Errorf("gocraft: block.break has %d fields, want 5", len(fields))
	}
	player, err := playerFrom(fields[0])
	if err != nil {
		return nil, err
	}
	pos, err := positionFrom(fields[1])
	if err != nil {
		return nil, err
	}
	block, err := blockFrom(fields[2])
	if err != nil {
		return nil, err
	}
	tool, err := stringFrom(fields[3], "block.break tool")
	if err != nil {
		return nil, err
	}
	permissions, err := permissionsFrom(fields[4])
	if err != nil {
		return nil, err
	}
	return &BlockBreakEvent{Player: player, Pos: pos, Block: block, Tool: tool, permissions: permissions}, nil
}

// PlayerJoinEvent is the player.join event.
//
// Observational: the tick does not wait, and nothing a handler does
// can prevent what already happened.
type PlayerJoinEvent struct {
	Player Player

	// permissions is what the host resolved before dispatch. Unexported
	// because the schema says an injected field surfaces as a query
	// rather than as a map to rummage through, and because a handler
	// that could write to it would be answering its own question.
	permissions map[string]bool
}

func (*PlayerJoinEvent) Type() string { return EventPlayerJoin }

// Can reports whether the acting player holds a permission node.
//
// Already resolved: the host answers every node the manifest subscribed
// to and ships the answers inside the event, so this is a map lookup
// rather than a round trip taken while the tick waits.
//
// A node the manifest never declared reads false, because the host was
// never asked about it. That is a manifest bug, not a denial.
func (e *PlayerJoinEvent) Can(node string) bool { return e.permissions[node] }

// OnPlayerJoin registers a handler for player.join.
//
// Typed, so there is no event name to misspell: the parameter is the
// subscription. On accepts a name for anything this build does not know.
func (e *Events) OnPlayerJoin(handler func(*PlayerJoinEvent)) error {
	return e.On(EventPlayerJoin, func(event Event) {
		if typed, ok := event.(*PlayerJoinEvent); ok {
			handler(typed)
		}
	})
}

func playerJoinFrom(fields []abi.Value) (*PlayerJoinEvent, error) {
	if len(fields) != 2 {
		return nil, fmt.Errorf("gocraft: player.join has %d fields, want 2", len(fields))
	}
	player, err := playerFrom(fields[0])
	if err != nil {
		return nil, err
	}
	permissions, err := permissionsFrom(fields[1])
	if err != nil {
		return nil, err
	}
	return &PlayerJoinEvent{Player: player, permissions: permissions}, nil
}

// eventFrom reads one dispatched event.
//
// A native event is decoded against the layout generated with it. Anything
// else is plugin-defined by construction — a provided type must contain a
// slash and no native name has one — so it goes to the positional reader
// rather than being refused. Which layout it should be read against is a
// fact this build cannot have: it belongs to the manifest of whichever
// plugin provides it.
func eventFrom(incoming *abi.Event) (Event, error) {
	if incoming == nil {
		return nil, fmt.Errorf("gocraft: missing event")
	}
	switch incoming.Type {
	case EventBlockBreak:
		return blockBreakFrom(incoming.Fields)
	case EventPlayerJoin:
		return playerJoinFrom(incoming.Fields)
	default:
		return customFrom(incoming)
	}
}
