// Code generated by protoc-gen-gocraft. DO NOT EDIT.
//
// Source: abi/v1/events.proto

package gocraft

import (
	"fmt"

	abi "github.com/GoCraft-MC/gocraft-abi/abi/v1"
)

// Event types, as a manifest spells them.
const (
	// Cancellable, blocks the tick, defaults to allow. Introduced in ABI 1.
	EventBlockBreak = "block.break"
	// Observational, never cancelled. Introduced in ABI 1.
	EventPlayerJoin = "player.join"
	// Cancellable, blocks the tick, defaults to allow. Introduced in ABI 1.
	EventBlockPlace = "block.place"
	// Observational, never cancelled. Introduced in ABI 1.
	EventPlayerQuit = "player.quit"
	// Cancellable, blocks the tick, defaults to allow. Introduced in ABI 1.
	EventPlayerChat = "player.chat"
	// Cancellable, blocks the tick, defaults to allow. Introduced in ABI 1.
	EventPlayerCommand = "player.command"
	// Cancellable, blocks the tick, defaults to allow. Introduced in ABI 1.
	EventPlayerDamage = "player.damage"
	// Observational, never cancelled. Introduced in ABI 1.
	EventPlayerDeath = "player.death"
	// Observational, never cancelled. Introduced in ABI 1.
	EventPlayerRespawn = "player.respawn"
	// Cancellable, blocks the tick, defaults to allow. Introduced in ABI 1.
	EventPlayerTeleport = "player.teleport"
	// Cancellable, blocks the tick, defaults to allow. Introduced in ABI 1.
	EventPlayerInteract = "player.interact"
	// Cancellable, blocks the tick, defaults to allow. Introduced in ABI 1.
	EventInventoryClick = "inventory.click"
	// Cancellable, blocks the tick, defaults to allow. Introduced in ABI 1.
	EventItemUse = "item.use"
	// Cancellable, blocks the tick, defaults to allow. Introduced in ABI 1.
	EventEntityDamage = "entity.damage"
)

// BlockBreakEvent is the block.break event.
//
// Cancellable, and dispatched while the tick waits. Every subscriber
// shares one budget for the whole event, so a handler that takes its
// time is taking it from the others.
type BlockBreakEvent struct {
	// Snapshot: changing this field does not change the server.
	Player *PlayerRef
	// Snapshot: changing this field does not change the server.
	Pos BlockPos
	// Snapshot: changing this field does not change the server.
	Block Block
	// Snapshot: changing this field does not change the server.
	Tool string

	// permissions is what the host resolved before dispatch. Unexported
	// because the schema says an injected field surfaces as a query
	// rather than as a map to rummage through, and because a handler
	// that could write to it would be answering its own question.
	permissions map[string]bool
}

func (*BlockBreakEvent) Type() string { return EventBlockBreak }

// Can reports whether the acting player holds a permission node.
//
// Already resolved: the host answers every node the manifest subscribed
// to and ships the answers inside the event, so this is a map lookup
// rather than a round trip taken while the tick waits.
//
// A node the manifest never declared reads false, because the host was
// never asked about it. That is a manifest bug, not a denial.
func (e *BlockBreakEvent) Can(node string) bool { return e.permissions[node] }

// OnBlockBreak registers a handler for block.break.
//
// Typed, so there is no event name to misspell: the parameter is the
// subscription. On accepts a name for anything this build does not know.
//
// EventControl carries cancellation, just as it does for custom events.
func (e *Events) OnBlockBreak(handler func(*BlockBreakEvent, EventControl)) error {
	if handler == nil {
		return fmt.Errorf("gocraft: event handler is required")
	}
	return e.On(EventBlockBreak, func(event Event, control EventControl) {
		if typed, ok := event.(*BlockBreakEvent); ok {
			handler(typed, control)
		}
	})
}

func blockBreakFrom(fields []abi.Value, sink *effects) (*BlockBreakEvent, error) {
	if len(fields) != 5 {
		return nil, fmt.Errorf("gocraft: block.break has %d fields, want 5", len(fields))
	}
	player, err := playerFrom(fields[0], sink)
	if err != nil {
		return nil, err
	}
	pos, err := positionFrom(fields[1])
	if err != nil {
		return nil, err
	}
	block, err := blockFrom(fields[2])
	if err != nil {
		return nil, err
	}
	tool, err := stringFrom(fields[3], "block.break tool")
	if err != nil {
		return nil, err
	}
	permissions, err := permissionsFrom(fields[4])
	if err != nil {
		return nil, err
	}
	return &BlockBreakEvent{Player: player, Pos: pos, Block: block, Tool: tool, permissions: permissions}, nil
}

// PlayerJoinEvent is the player.join event.
//
// Observational: the tick does not wait, and nothing a handler does
// can prevent what already happened.
type PlayerJoinEvent struct {
	// Snapshot: changing this field does not change the server.
	Player *PlayerRef

	// permissions is what the host resolved before dispatch. Unexported
	// because the schema says an injected field surfaces as a query
	// rather than as a map to rummage through, and because a handler
	// that could write to it would be answering its own question.
	permissions map[string]bool
}

func (*PlayerJoinEvent) Type() string { return EventPlayerJoin }

// Can reports whether the acting player holds a permission node.
//
// Already resolved: the host answers every node the manifest subscribed
// to and ships the answers inside the event, so this is a map lookup
// rather than a round trip taken while the tick waits.
//
// A node the manifest never declared reads false, because the host was
// never asked about it. That is a manifest bug, not a denial.
func (e *PlayerJoinEvent) Can(node string) bool { return e.permissions[node] }

// OnPlayerJoin registers a handler for player.join.
//
// Typed, so there is no event name to misspell: the parameter is the
// subscription. On accepts a name for anything this build does not know.
//
// Observational listeners receive only the payload, with no cancellation.
func (e *Events) OnPlayerJoin(handler func(*PlayerJoinEvent)) error {
	if handler == nil {
		return fmt.Errorf("gocraft: event handler is required")
	}
	return e.On(EventPlayerJoin, func(event Event, control EventControl) {
		if typed, ok := event.(*PlayerJoinEvent); ok {
			handler(typed)
		}
	})
}

func playerJoinFrom(fields []abi.Value, sink *effects) (*PlayerJoinEvent, error) {
	if len(fields) != 2 {
		return nil, fmt.Errorf("gocraft: player.join has %d fields, want 2", len(fields))
	}
	player, err := playerFrom(fields[0], sink)
	if err != nil {
		return nil, err
	}
	permissions, err := permissionsFrom(fields[1])
	if err != nil {
		return nil, err
	}
	return &PlayerJoinEvent{Player: player, permissions: permissions}, nil
}

// BlockPlaceEvent is the block.place event.
//
// Cancellable, and dispatched while the tick waits. Every subscriber
// shares one budget for the whole event, so a handler that takes its
// time is taking it from the others.
type BlockPlaceEvent struct {
	// Snapshot: changing this field does not change the server.
	Player *PlayerRef
	// Snapshot: changing this field does not change the server.
	Pos BlockPos
	// Snapshot: changing this field does not change the server.
	Block Block
	// Snapshot: changing this field does not change the server.
	Replaced Block
	// Snapshot: changing this field does not change the server.
	Dimension int64

	// permissions is what the host resolved before dispatch. Unexported
	// because the schema says an injected field surfaces as a query
	// rather than as a map to rummage through, and because a handler
	// that could write to it would be answering its own question.
	permissions map[string]bool
}

func (*BlockPlaceEvent) Type() string { return EventBlockPlace }

// Can reports whether the acting player holds a permission node.
//
// Already resolved: the host answers every node the manifest subscribed
// to and ships the answers inside the event, so this is a map lookup
// rather than a round trip taken while the tick waits.
//
// A node the manifest never declared reads false, because the host was
// never asked about it. That is a manifest bug, not a denial.
func (e *BlockPlaceEvent) Can(node string) bool { return e.permissions[node] }

// OnBlockPlace registers a handler for block.place.
//
// Typed, so there is no event name to misspell: the parameter is the
// subscription. On accepts a name for anything this build does not know.
//
// EventControl carries cancellation, just as it does for custom events.
func (e *Events) OnBlockPlace(handler func(*BlockPlaceEvent, EventControl)) error {
	if handler == nil {
		return fmt.Errorf("gocraft: event handler is required")
	}
	return e.On(EventBlockPlace, func(event Event, control EventControl) {
		if typed, ok := event.(*BlockPlaceEvent); ok {
			handler(typed, control)
		}
	})
}

func blockPlaceFrom(fields []abi.Value, sink *effects) (*BlockPlaceEvent, error) {
	if len(fields) != 6 {
		return nil, fmt.Errorf("gocraft: block.place has %d fields, want 6", len(fields))
	}
	player, err := playerFrom(fields[0], sink)
	if err != nil {
		return nil, err
	}
	pos, err := positionFrom(fields[1])
	if err != nil {
		return nil, err
	}
	block, err := blockFrom(fields[2])
	if err != nil {
		return nil, err
	}
	replaced, err := blockFrom(fields[3])
	if err != nil {
		return nil, err
	}
	dimension, err := int64From(fields[4], "block.place dimension")
	if err != nil {
		return nil, err
	}
	permissions, err := permissionsFrom(fields[5])
	if err != nil {
		return nil, err
	}
	return &BlockPlaceEvent{Player: player, Pos: pos, Block: block, Replaced: replaced, Dimension: dimension, permissions: permissions}, nil
}

// PlayerQuitEvent is the player.quit event.
//
// Observational: the tick does not wait, and nothing a handler does
// can prevent what already happened.
type PlayerQuitEvent struct {
	// Snapshot: changing this field does not change the server.
// eventFrom reads one dispatched event.
//
// A native event is decoded against the layout generated with it. Anything
// else is plugin-defined by construction — a provided type must contain a
// slash and no native name has one — so it goes to the positional reader
// rather than being refused. Which layout it should be read against is a
// fact this build cannot have: it belongs to the manifest of whichever
// plugin provides it.
func eventFrom(incoming *abi.Event, sink *effects) (Event, error) {
	if incoming == nil {
		return nil, fmt.Errorf("gocraft: missing event")
	}
	switch incoming.Type {
	case EventBlockBreak:
		return blockBreakFrom(incoming.Fields, sink)
	case EventPlayerJoin:
		return playerJoinFrom(incoming.Fields, sink)
	default:
		return customFrom(incoming, sink)
	}
}
